### ISSUE TITLE
Initial vagrant up build fails due to missing gcc puppet module and missing riemann client gem

### ISSUE THREAD

**Issue by landonclark** [garethr/riemann-vagrant#1]
I was referred to your project from the Riemann quickstart page and I ran into two issues trying to use your Vagrant install:
1. gcc puppet module was missing.  I fixed this by adding: 

``` ruby
mod 'puppetlabs/gcc
```

to the Puppetfile
2. I needed to manually run 

```
gem install riemann-client
```

in the vagrant guest.

Thanks for putting this together.  I just wanted to play with Riemann and you made it much easier!

**Comment by garethr** [comment]
Thanks, sorry I completely missed this. I've just given the source riemann puppet module a good kicking and updated the dependencies. This should work much better now.
