### ISSUE TITLE
Permission error in the log files

### ISSUE THREAD

**Issue by rantav** [garethr/riemann-vagrant#3]
Hi @garethr thanks for this, it's a real time saver!
As I was trying out the ubuntu recipe I noticed that the logs aren't getting written.

```
vagrant@precise64:~$ tail -F /var/log/riemann.log
tail: cannot open `/var/log/riemann.log' for reading: No such file or directory
```

This fixes it templrarily, but I guess you want to fix this permanently...

```
vagrant@precise64:~$ sudo touch /var/log/riemann.log
vagrant@precise64:~$ sudo chown riemann:riemann /var/log/riemann.log
vagrant@precise64:~$ sudo service riemann restart
```

cheers

**Comment by garethr** [comment]
Thanks for the issue report. I've fixed this in the upstream puppet module and then update this repo. If you already have it setup you can do `bundle exec librarian-puppet update garethr/riemann` and then `vagrant provision` should see the log file always set with the correct permissions.
